const mongoose = require('mongoose');

const AnalysisRecordSchema = new mongoose.Schema({
  stockCode: { type: String, required: true },
  riskProfile: { type: String },
  marketSentiment: { type: String }, // Optional user input
  status: { type: String, default: 'pending', enum: ['pending', 'processing', 'completed', 'failed'] },
  createdAt: { type: Date, default: Date.now },
  
  consultantOutput: {
    scores: {
      sentiment: Number,
      risk: Number,
      fundamental: Number
    },
    marketInfoSummary: String,
    references: [String],
    rawMarketData: Object // For storing the detailed JSON data
  },

  debatePlan: [String], // List of topics/dimensions generated by Host

  debateTranscript: [
    {
      round: Number,
      topic: String, // The specific dimension being discussed
      speaker: String,
      content: String,
      timestamp: { type: Date, default: Date.now }
    }
  ],

  finalResult: {
    decision: String,
    reasoning: String,
    confidence: Number
  }
});

module.exports = mongoose.model('AnalysisRecord', AnalysisRecordSchema);
